"""add_original_filename

Revision ID: 2cbea98c402b
Revises: c91d7857c710
Create Date: 2026-03-30 15:29:44.032362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbea98c402b'
down_revision: Union[str, Sequence[str], None] = 'c91d7857c710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'original_filename')
    # ### end Alembic commands ###
