"""add_error_detail_to_invoices

Revision ID: eaeb574c5dc3
Revises: 6ef6ff8a213f
Create Date: 2026-04-03 22:00:25.788234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaeb574c5dc3'
down_revision: Union[str, Sequence[str], None] = '6ef6ff8a213f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
