"""add_error_detail_to_invoices

Revision ID: 6ef6ff8a213f
Revises: 3ea0a8e64e36
Create Date: 2026-04-03 10:59:46.232548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef6ff8a213f'
down_revision: Union[str, Sequence[str], None] = '3ea0a8e64e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
